spring:
 datasource:
  username: dbuser
  password: '{cipher}AQAjndAYlUJeodNM9R3iLKj1WUgFJ4xRvkuewQ8RHKXPPp8szwt6OhX80NlB47nhfXw4XGeqbNs53oaCVpIcc66No6iWjU8/VxUebG8i2H2DjnBhqqwYvkr6uHnnDaIYq2Vwo1MpiQPYqFe09xYbsBCLjRRyPfatuEDLcp0zbJS9ySakH8+zC7iRO5/KCDyGhrlNjPVIrp7s1FYEsoEVX9afystEeQreVMkSyn2DPTJ7kdn9HC0K3pFx7pqyYNMnPiOKWmkYDN/rfSS5AEtSRx5c6XyDZz1Srm8KQVV8FWzikx162ycanbsZrMQAcKACUZ8DvktNwxsvgQ+6df82EX3qW6dPLt3gqWIS3LtoLQ6KDJbedOzUw5Odo6w66UDp3GA='